### ISSUE TITLE
problem deleting field on survey

### ISSUE THREAD

**Issue by fmacias64** [ushahidi/platform-release#23]
On a new survey , once a field is created it cannot be deleted.
The message that appears on JS console is ..

vendor.7772a1d529dcfbc6af6d.js:102 DELETE http://carreteras.intelect.com.mx/api/v3/forms/10/attributes/39?order=asc&orderby=priority 500 (Internal Server Error)

and

vendor.7772a1d529dcfbc6af6d.js:102 Possibly unhandled rejection: {"data":{"errors":[{"status":500,"message":"This cache store does not support tagging."}]}," ...

this message "This cache store does not support tagging." appeared also with no consequence whe creating new surveys. (ataching image)
![Surveys - Carreteras](https://user-images.githubusercontent.com/6963767/73320731-ead02280-4205-11ea-99c1-0e5fd62823e2.png)

using docker version  https://github.com/ushahidi/platform-release.git, as of Dec 5 2019

My .env ..

APP_ENV=local
APP_DEBUG=false
APP_KEY=h1N8OnHDGNzCbA$wfoveR(rXGHn0sq%o
APP_TIMEZONE=UTC

DB_CONNECTION=mysql
DB_HOST=mysql
DB_DATABASE=ushahidi
DB_USERNAME= ****
DB_PASSWORD= ****
DB_TYPE=MySQLi

CACHE_DRIVER=file
QUEUE_DRIVER=sync
-----

**Comment by rowasc** [comment]
@fmacias64 can you try switching to `array` (a test-env-only setting for the cache driver) in `run.sh`, destroy the container, rebuild it, and let us know if it works for you?

1 .Edit run.sh to use
`CACHE_DRIVER=array`

2. recreate environment
```
docker-compose stop ; 
docker-compose rm -f;
docker-compose build;
docker-compose up
```

We will update the docs to mention this issue with the file CACHE_DRIVER and survey creation/tags. 
Thanks  so much for reporting it . 


@tuxpiper we probably should add memcached or redis to this default setup since we can't use file sadly for some features (or maybe it's already available and I just couldn't find that 🤔 )

**Comment by fmacias64** [comment]
¡Muchas gracias Romina !

**Comment by rowasc** [comment]
De nada, espero que haya funcionado :tada:

**Comment by tuxpiper** [comment]
Created PR #24 to address this

**Comment by tuxpiper** [comment]
This should be fixed now
